services:
  candycane-spring:
    container_name: candycane-spring
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./secret.properties:/app/secret.properties
    restart: unless-stopped
    working_dir: /app
    ports:
      - 8080:8080
    cap_drop:
      - ALL